### ISSUE TITLE
Custom path for .dockerignore

### ISSUE THREAD

**Issue by haos616** [cloud66-oss/habitus#109]
Sometimes it's very convenient to have different files in the same context for different services, that would not add the unnecessary files to the context

**Comment by khash** [comment]
This would require support from Docker (as per https://github.com/moby/moby/issues/12886 it's not available yet and there is a lengthy discusson on that).

We certainly can try and copy the entire context over to a new place and have our own convention to specify the `.dockerignore` file that's going to be selected for any specific build, but that would break one of the main design principles of Habitus which is it doesn't have to exist for a single step build to work.
