### ISSUE TITLE
Build for step opencv failed due to Invalid header type

### ISSUE THREAD

**Issue by igaldahan** [cloud66-oss/habitus#111]
Hi have habitus file

build:
  version: 2016-03-14
  steps:
    ffmpeg:
      name: ffmpeg
      dockerfile: Dockerfile.ffmpeg 
      artifacts:
         - /usr/local/bin/ffmpeg
         - /usr/local/bin/ffplay
         - /usr/local/bin/ffprobe
    opencv:
      name: opencv
      dockerfile: Dockerfile.opencv 
      artifacts:
         - /usr/local
      depends_on: 
         - ffmpeg

and i got result at the end of lines:

2018/11/28 18:11:57 ▶ Build for step opencv failed due to Invalid header type 

what does it mean? where could be the issue?

**Comment by khash** [comment]
Can you build Dockerfile.opencv itself independtly and directly using `docker build`?
